_wandb:
    value:
        cli_version: 0.25.1
        e:
            4xqo1lvn25zlm8xqwoecqe57t3ubbv30:
                codePath: runtime_model_draft_latest.py
                codePathLocal: runtime_model_draft_latest.py
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "5368709120"
                        used: "1207234560"
                email: aaokolo@ucsc.edu
                executable: /usr/local/bin/python
                git:
                    commit: 4339a77a9423541787fd001d0db669ccb559a5fa
                    remote: https://github.com/andreaoko/CMPM-17---Final-Project
                gpu: NVIDIA RTX 4000 Ada Generation
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 6144
                      memoryTotal: "21469593600"
                      name: NVIDIA RTX 4000 Ada Generation
                      uuid: GPU-4d21dbd2-607a-5808-aacc-daf2e46ec694
                host: 0d1e24083292
                memory:
                    total: "540656259072"
                os: Linux-6.8.0-40-generic-x86_64-with-glibc2.39
                program: /workspace/repo/CMPM-17---Final-Project/runtime_model_draft_latest.py
                python: CPython 3.12.3
                root: /workspace/repo/CMPM-17---Final-Project
                startedAt: "2026-03-16T03:31:23.058597Z"
                writerId: 4xqo1lvn25zlm8xqwoecqe57t3ubbv30
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 13
            "4": 3.12.3
            "5": 0.25.1
            "12": 0.25.1
            "13": linux-x86_64
