_wandb:
    value:
        cli_version: 0.25.0
        e:
            j1kznlhs66ist9ka3w74xux7r32jb865:
                apple:
                    ecpuCores: 4
                    gpuCores: 10
                    memoryGb: 8
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "9663676416"
                codePath: runtime_model_draft_latest.py
                codePathLocal: runtime_model_draft_latest.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "214112587776"
                email: aaokolo@ucsc.edu
                executable: /usr/local/bin/python3
                git:
                    commit: a620dca0bba979f08bd18bb350944878afa2b5eb
                    remote: https://github.com/andreaoko/CMPM-17---Final-Project.git
                host: Andreas-MacBook-Pro.local
                memory:
                    total: "8589934592"
                os: macOS-15.0.1-arm64-arm-64bit-Mach-O
                program: /Users/andreaokolo/CMPM-17---Final-Project/runtime_model_draft_latest.py
                python: CPython 3.14.2
                root: /Users/andreaokolo/CMPM-17---Final-Project
                startedAt: "2026-03-15T21:58:18.316205Z"
                writerId: j1kznlhs66ist9ka3w74xux7r32jb865
        m: []
        python_version: 3.14.2
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 13
            "4": 3.14.2
            "5": 0.25.0
            "12": 0.25.0
            "13": darwin-arm64
